### ISSUE TITLE
MiniCPM-2B 导出onnx时,出现AttributeError: 'MiniCPMFlashAttention2' object has no attribute 'q_proj'. Did you mean: 'o_proj'?

### ISSUE THREAD

**Issue by Simease** [DakeQQ/Native-LLM-for-Android#12]
MiniCPM-2B 导出onnx时，在bais问题解决后，又出现了新的问题，我运行MiniCPM_Export.py：
在modeling_modified_A](https://github.com/DakeQQ/Native-LLM-for-Android/tree/main/Export_ONNX/MiniCPM/MiniCPM-2B/modeling_modified_A/modeling_minicpm.py的第494行
 query_states = self.q_proj(hidden_states)
 key_states = self.k_proj(hidden_states)
 value_states = self.v_proj(hidden_states)
貌似self没有q_proj、k_proj、v_proj对象
+++++++++++++++++++++++++++++++++++++++++++
Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes, but the current dype in MiniCPMForCausalLM is torch.float32. You should run training or inference using Automatic Mixed-Precision via the `with torch.autocast(device_type='torch_device'):` decorator, or load the model with the `torch_dtype` argument. Example: `model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="flash_attention_2", torch_dtype=torch.float16)`
Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes, but the current dype in MiniCPMModel is torch.float32. You should run training or inference using Automatic Mixed-Precision via the `with torch.autocast(device_type='torch_device'):` decorator, or load the model with the `torch_dtype` argument. Example: `model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="flash_attention_2", torch_dtype=torch.float16)`
Some weights of MiniCPMForCausalLM were not initialized from the model checkpoint at /home/jj/LLM/Native-LLM-for-Android-main/checkpoints/MiniCPM/MiniCPM-2B-dpo-fp32 and are newly initialized: ['model.layers.0.self_attn.qkv_proj.weight', 'model.layers.1.self_attn.qkv_proj.weight', 'model.layers.10.self_attn.qkv_proj.weight', 'model.layers.11.self_attn.qkv_proj.weight', 'model.layers.12.self_attn.qkv_proj.weight', 'model.layers.13.self_attn.qkv_proj.weight', 'model.layers.14.self_attn.qkv_proj.weight', 'model.layers.15.self_attn.qkv_proj.weight', 'model.layers.16.self_attn.qkv_proj.weight', 'model.layers.17.self_attn.qkv_proj.weight', 'model.layers.18.self_attn.qkv_proj.weight', 'model.layers.19.self_attn.qkv_proj.weight', 'model.layers.2.self_attn.qkv_proj.weight', 'model.layers.20.self_attn.qkv_proj.weight', 'model.layers.21.self_attn.qkv_proj.weight', 'model.layers.22.self_attn.qkv_proj.weight', 'model.layers.23.self_attn.qkv_proj.weight', 'model.layers.24.self_attn.qkv_proj.weight', 'model.layers.25.self_attn.qkv_proj.weight', 'model.layers.26.self_attn.qkv_proj.weight', 'model.layers.27.self_attn.qkv_proj.weight', 'model.layers.28.self_attn.qkv_proj.weight', 'model.layers.29.self_attn.qkv_proj.weight', 'model.layers.3.self_attn.qkv_proj.weight', 'model.layers.30.self_attn.qkv_proj.weight', 'model.layers.31.self_attn.qkv_proj.weight', 'model.layers.32.self_attn.qkv_proj.weight', 'model.layers.33.self_attn.qkv_proj.weight', 'model.layers.34.self_attn.qkv_proj.weight', 'model.layers.35.self_attn.qkv_proj.weight', 'model.layers.36.self_attn.qkv_proj.weight', 'model.layers.37.self_attn.qkv_proj.weight', 'model.layers.38.self_attn.qkv_proj.weight', 'model.layers.39.self_attn.qkv_proj.weight', 'model.layers.4.self_attn.qkv_proj.weight', 'model.layers.5.self_attn.qkv_proj.weight', 'model.layers.6.self_attn.qkv_proj.weight', 'model.layers.7.self_attn.qkv_proj.weight', 'model.layers.8.self_attn.qkv_proj.weight', 'model.layers.9.self_attn.qkv_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Part_A export start...
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/jj/LLM/Native-LLM-for-Android-main/Export_ONNX/MiniCPM/MiniCPM-2B/MiniCPM_Export.py", line 88, in <module>
    torch.onnx.export(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 551, in export
    _export(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 1648, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 1170, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 1046, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 950, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/jit/_trace.py", line 1497, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/jit/_trace.py", line 141, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/jit/_trace.py", line 132, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/jj/.cache/huggingface/modules/transformers_modules/MiniCPM-2B-dpo-fp32/modeling_minicpm.py", line 1065, in forward
    hidden_states, self.save_key[i], self.save_value[i] = self.model.layers[i](
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/jj/.cache/huggingface/modules/transformers_modules/MiniCPM-2B-dpo-fp32/modeling_minicpm.py", line 714, in forward
    hidden_states_temp, past_key_states, past_value_states = self.self_attn(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/jj/.cache/huggingface/modules/transformers_modules/MiniCPM-2B-dpo-fp32/modeling_minicpm.py", line 494, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MiniCPMFlashAttention2' object has no attribute 'q_proj'. Did you mean: 'o_proj'?

**Comment by DakeQQ** [comment]
对于在导出过程中遇到的不佳体验，我深表歉意。您遇到的问题是由于使用了针对GPU设备优化的`MiniCPMFlashAttention2`。为了进行ONNX导出，我们对原始代码进行了最小限度的修改，主要是在大约第648行修改了`MiniCPMSdpaAttention`函数，而保持Flash Attention 2的代码不变。为了确保导出过程更加顺畅，请确认您正在使用CPU，并且导出时调用了`MiniCPMSdpaAttention`函数 `(MINICPM_ATTENTION_CLASSES = "sdpa")`。此外，我们在最新的自检中已经解决了其他识别出的问题。我们恳请再次给予机会，使用最新的导出代码来获取MiniCPM-2B模型。

**Comment by Simease** [comment]
> 对于在导出过程中遇到的不佳体验，我们深表歉意。您遇到的问题是由于使用了针对GPU设备优化的`MiniCPMFlashAttention2`。为了进行ONNX导出，我们对原始代码进行了最小限度的修改，主要是在大约第648行修改了`MiniCPMSdpaAttention`函数，而保持Flash Attention 2的代码不变。为了确保导出过程更加顺畅，请确认您正在使用CPU，并且导出时调用了`MiniCPMSdpaAttention`函数 `(MINICPM_ATTENTION_CLASSES = "sdpa")`。此外，我们在最新的自检中已经解决了其他识别出的问题。我们恳请再次给予机会，使用最新的导出代码来获取MiniCPM-2B模型。

在使用您这边最新的minicpm2B导出代码的过程中，又出现了新的问题，具体来说是：
modeling_minicpm.py中的大约496行中：
‘’‘’
bsz, q_len,_ = hidden_states.size()
query_states = self.q_proj(hidden_states)
key_states = self.k_proj(hidden_states)
value_states = self.v_proj(hidden_states)

# Flash attention requires the input to have the shape
# batch_size x seq_length x head_dim x hidden_dim
# therefore we just need to keep the original shape
query_states = query_states.view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
key_states = key_states.view(bsz, q_len, self.num_key_value_heads, self.head_dim).transpose(1, 2)
value_states = value_states.view(bsz, q_len, self.num_key_value_heads, self.head_dim).transpose(1, 2)
‘’‘’
首先我的 hidden_states.size()是torch.Size([10, 2304])，在后续的过程中又导致了query_states无法view为（bsz, q_len, self.num_heads, self.head_dim）形状的错误。报错如下（**如果有可能不知您是否方便发一份导出的文件到这个邮箱1149707840@qq.com 万分感谢**
）：
Traceback (most recent call last):
  File "/home/jj/LLM/Native-LLM-for-Android-main/Export_ONNX/MiniCPM/MiniCPM-2B/MiniCPM_Export.py", line 74, in <module>
    torch.onnx.export(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 551, in export
    _export(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 1648, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 1170, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 1046, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 950, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/jit/_trace.py", line 1497, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/jit/_trace.py", line 141, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/jit/_trace.py", line 132, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/jj/.cache/huggingface/modules/transformers_modules/MiniCPM-2B-dpo-fp32/modeling_minicpm.py", line 1059, in forward
    hidden_states, self.save_key[i], self.save_value[i] = self.model.layers[i](
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/jj/.cache/huggingface/modules/transformers_modules/MiniCPM-2B-dpo-fp32/modeling_minicpm.py", line 708, in forward
    hidden_states_temp, past_key_states, past_value_states = self.self_attn(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/jj/.cache/huggingface/modules/transformers_modules/MiniCPM-2B-dpo-fp32/modeling_minicpm.py", line 496, in forward
    query_states = query_states.view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
RuntimeError: shape '[10, 2304, 36, 64]' is invalid for input of size 23040

**Comment by Simease** [comment]
> 对于在导出过程中遇到的不佳体验，我们深表歉意。您遇到的问题是由于使用了针对GPU设备优化的`MiniCPMFlashAttention2`。为了进行ONNX导出，我们对原始代码进行了最小限度的修改，主要是在大约第648行修改了`MiniCPMSdpaAttention`函数，而保持Flash Attention 2的代码不变。为了确保导出过程更加顺畅，请确认您正在使用CPU，并且导出时调用了`MiniCPMSdpaAttention`函数 `(MINICPM_ATTENTION_CLASSES = "sdpa")`。此外，我们在最新的自检中已经解决了其他识别出的问题。我们恳请再次给予机会，使用最新的导出代码来获取MiniCPM-2B模型。

```
在使用您这边最新的minicpm2B导出代码的过程中，又出现了新的问题，具体来说是：
modeling_minicpm.py中的大约496行中：
‘’‘’
bsz, q_len,_ = hidden_states.size()
query_states = self.q_proj(hidden_states)
key_states = self.k_proj(hidden_states)
value_states = self.v_proj(hidden_states)

# Flash attention requires the input to have the shape
# batch_size x seq_length x head_dim x hidden_dim
# therefore we just need to keep the original shape
query_states = query_states.view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
key_states = key_states.view(bsz, q_len, self.num_key_value_heads, self.head_dim).transpose(1, 2)
value_states = value_states.view(bsz, q_len, self.num_key_value_heads, self.head_dim).transpose(1, 2)
‘’‘’
首先我的 hidden_states.size()是torch.Size([10, 2304])，在后续的过程中又导致了query_states无法view为（bsz, q_len, self.num_heads, self.head_dim）形状的错误。报错如下（**如果有可能不知您是否方便发一份导出的文件到这个邮箱1149707840@qq.com 万分感谢**
）：
Traceback (most recent call last):
  File "/home/jj/LLM/Native-LLM-for-Android-main/Export_ONNX/MiniCPM/MiniCPM-2B/MiniCPM_Export.py", line 74, in <module>
    torch.onnx.export(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 551, in export
    _export(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 1648, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 1170, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 1046, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/onnx/utils.py", line 950, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/jit/_trace.py", line 1497, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/jit/_trace.py", line 141, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/jit/_trace.py", line 132, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/jj/.cache/huggingface/modules/transformers_modules/MiniCPM-2B-dpo-fp32/modeling_minicpm.py", line 1059, in forward
    hidden_states, self.save_key[i], self.save_value[i] = self.model.layers[i](
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/jj/.cache/huggingface/modules/transformers_modules/MiniCPM-2B-dpo-fp32/modeling_minicpm.py", line 708, in forward
    hidden_states_temp, past_key_states, past_value_states = self.self_attn(
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jj/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/jj/.cache/huggingface/modules/transformers_modules/MiniCPM-2B-dpo-fp32/modeling_minicpm.py", line 496, in forward
    query_states = query_states.view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
RuntimeError: shape '[10, 2304, 36, 64]' is invalid for input of size 23040
```

**Comment by DakeQQ** [comment]
您仍然调用了我们未修改的Flash Attention 2函数。请稍等，我们将发送给您一个包含已修改的Flash Attention 2模块的脚本。

**Comment by DakeQQ** [comment]
我们已将修改后的脚本发送到1149707840@qq.com，请查收并随时联系我们。

**Comment by Simease** [comment]
> 我们已将修改后的脚本发送到[1149707840@qq.com](mailto:1149707840@qq.com)，请查收并随时联系我们。

万分感谢，已经收到了您这边发送的脚本，而且可以成功导出onnx文件，不过我有一点不明白的是，我观察到其他模型只使用了一个ort文件（例如您给出的示例），而minicpm2b导出了A和B一共2个onnx目录，我是需要将A和B两个onnx都转为ort文件，然后放到assert目录中吗

**Comment by DakeQQ** [comment]
是的。MiniCPM-2B 模型被拆分成两个文件，以确保每个文件在进行 int8 量化后大小都保持在 2GB 以下。这样做是因为 onnxsim 工具仅支持小于 2GB 的文件，并且如果在 Android Studio 的 assets 文件夹中放置单个大文件，可能会导致构建错误。此外，使用 ONNX Runtime 的 C++ 代码加载模型时（如果模型以 `external_format=True` 的方式存储），还需要额外的代码来实现加载功能，而这些代码目前并未包含在 `project.cpp` 文件中。

**Comment by Simease** [comment]
> 是的。MiniCPM-2B 模型被拆分成两个文件，以确保每个文件在进行 int8 量化后大小都保持在 2GB 以下。这样做是因为 onnxsim 工具仅支持小于 2GB 的文件，并且如果在 Android Studio 的 assets 文件夹中放置单个大文件，可能会导致构建错误。此外，使用 ONNX Runtime 的 C++ 代码加载模型时（如果模型以 `external_format=True` 的方式存储），还需要额外的代码来实现加载功能，而这些代码目前并未包含在 `project.cpp` 文件中。

请问是否有公开这部分代码的想法或者方便分享这部分内容

**Comment by DakeQQ** [comment]
我忘了大文件加载代码放在哪里了，需要一点时间来找一找。

**Comment by Simease** [comment]
> 我忘了大文件加载代码放在哪里了，需要一点时间来找一找。

好的，期待您的结果

**Comment by Simease** [comment]
> 对于在导出过程中遇到的不佳体验，我们深表歉意。您遇到的问题是由于使用了针对GPU设备优化的`MiniCPMFlashAttention2`。为了进行ONNX导出，我们对原始代码进行了最小限度的修改，主要是在大约第648行修改了`MiniCPMSdpaAttention`函数，而保持Flash Attention 2的代码不变。为了确保导出过程更加顺畅，请确认您正在使用CPU，并且导出时调用了`MiniCPMSdpaAttention`函数 `(MINICPM_ATTENTION_CLASSES = "sdpa")`。此外，我们在最新的自检中已经解决了其他识别出的问题。我们恳请再次给予机会，使用最新的导出代码来获取MiniCPM-2B模型。

请问您这边是否更新了minicpm1B的最新导出代码，因为我在尝试使用1B的最新代码出现了相同的错误。

**Comment by DakeQQ** [comment]
我们已将修改后的MiniCPM-1B脚本发送到[1149707840@qq.com](mailto:1149707840@qq.com)，请查收并随时联系我们。

**Comment by DakeQQ** [comment]
您好，我们已经找到了加载外部ONNX数据的代码。请参考此链接[MiniCPM_2B_single_model_file](https://github.com/DakeQQ/Native-LLM-for-Android/tree/main/MiniCPM_ONNX/MiniCPM_2B_single_model_file)尝试使用。请注意，放置在assets文件夹中的单个文件如果大于3GB，在Android Studio构建过程中可能会导致错误。因此，建议将模型存储在具有访问权限的其他路径中。


主要变化是:
```
        if (file_name_A_external != "NONE") {
            const char* external_file_names[] = {file_name_A_external.c_str()};     // Add all external data file names here if your model uses multiple external files.
            const char* external_file_buffers[] = {fileBuffer_external.data()};     // Read external data into fileBuffers and add them here.
            size_t external_file_sizes[] = {fileBuffer_external.size()};            // Store the size of each fileBuffer here for multiple external data files.
            ort_runtime_A->AddExternalInitializersFromFilesInMemory(session_options_A, external_file_names, const_cast<char**>(external_file_buffers), external_file_sizes, 1);  // '1' indicates a single external file.
        }
```
